version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://user:password@postgres_db/eventdb
    ports:
      - "8000:8000"
    env_file:
      - .env
      
volumes:
  postgres_data:
